### ISSUE TITLE
Already a subscriber information not displaying in header (TFS 13250)

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/Subscription-Panel-Implementation#1]
Presentation: https://test-subscribe.oregonlive.com/Default_Instruction_Clean
CMS: http://prntscr.com/i0x6k4

Note that the "Already a Subscriber? Click here" should be appearing.  It should be an awful yellow which is...awful...but it should be there.

**Comment by mkoza178** [comment]
Ready to test!

**Comment by jvanzomeren** [comment]
this is fixed
