### ISSUE TITLE
Check Boxes (TFS 15829)

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/Subscription-Panel-Implementation#12]
When moving through the form. Per our legal team check boxes need to be unchecked workflow in some cases is having them pre-checked.   Additionally the form drops you past the check boxes and them shows as a warning that you did not check it.   Should focus on the check box

**Comment by mkoza178** [comment]
Jon, is this the same issue as the ezpay checkbox being auto-checked by default? Or is this something else?

**Comment by mkoza178** [comment]
Think we resolved, try now.

**Comment by jvanzomeren** [comment]
Terms and conditions box is unchecked and resolved.   We can control the EZ Pay optional box in Sol con however when we tested without checking EZ Pay the start was still entered as EZ- Pay Star

**Comment by mkoza178** [comment]
Verified, work item created for the team.

**Comment by mkoza178** [comment]
This is resolved. Please re-test.
