### ISSUE TITLE
Confirmation emails not generating (TFS 38696)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Subscription-Panel-Implementation#14]
Confirmation emails are not being generated for starts even though the setup mirrors production to trigger the email.  The following is for Flint Journal but we are experiencing the issue across all pubs:

![image](https://user-images.githubusercontent.com/25667903/38056003-d451e79e-32a0-11e8-86e5-2b3b4317eb37.png)

**Comment by mkoza178** [comment]
Agreed, not seeing any queue'd up. Work item created for dev team to review.

**Comment by mkoza178** [comment]
Please re-test.

**Comment by beckywallace** [comment]
Success.
