### ISSUE TITLE
EZ_pay offer not requiring the customer to check the box

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/Subscription-Panel-Implementation#19]
When entering a start on a ez pay account the terms and conditions are presented correctly with the box unchecked however will let you past without entering a X in the checkbox.   Mandatory function not working once we reset the box to open unchecked.

**Comment by mkoza178** [comment]
Test it out. 

I tested two use cases:
1. Where Ezpay is required, it throws an error requiring the user to continue. 
2. When it is optional it doesn't force you to select Ezpay to continue.
