### ISSUE TITLE
Portland LTE - "Address Required" as payment type option when address required checked on Promotion

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Subscription-Panel-Implementation#20]
When address required is selected on the promotion, the payment type dropdown in LTE contains an option for "Address Required":

![image](https://user-images.githubusercontent.com/25667903/38276182-ce2099e8-3759-11e8-89ce-10efd773ebc7.png)

**Comment by mkoza178** [comment]
Not a bug, you should never check 'address required' on Kiosk PIDs.
