### ISSUE TITLE
Header Text for "Click here" not scaling

### ISSUE THREAD

**Issue by JLewis12** [mkoza178/Subscription-Panel-Implementation#5]
If I change the font size on the Header Tab over 14px the words and link change to converts to "..."

![image](https://user-images.githubusercontent.com/26151269/35403235-f964f152-01b3-11e8-8673-03dfb9c77733.png)

![image](https://user-images.githubusercontent.com/26151269/35403296-20351726-01b4-11e8-83a8-e675921feb1c.png)

**Comment by JLewis12** [comment]
Also alignment is off.  I can not "Already a sub.." to align with "Click Here"

**Comment by JLewis12** [comment]
URL = Example_1

**Comment by mkoza178** [comment]
Check this preso: 
https://test-subscribe.oregonlive.com/Example_1MarcCopy

I deleted your formatting out and started from scratch and looks much better. I'm not sure what your formatting was doing exactly, but it caused issues.

**Comment by JLewis12** [comment]
The field for the Click Here (AlreadySubscriber.LinkText:) looks to only be valid for 10 characters -

Can we please have this increased?  The changes the LMG requested cause the field to display only "..." since the character count is large than 10.


![image](https://user-images.githubusercontent.com/26151269/36221706-d7ed2006-1173-11e8-84e2-3ff2e0737b11.png)

**Comment by mkoza178** [comment]
Checking on this.

**Comment by mkoza178** [comment]
Jason, it looks good on https://test-subscribe.oregonlive.com/Example_OMG2
Do you agree?

**Comment by JLewis12** [comment]
Good afternoon Marc,

Yes – the work around I have currently on my update does look okay.   The problem with it, is that it is a global color change for the header.  So Our BACK  button is also picked up with the assigned color.

I want to be able to assign the variance of the 2 fields as designed if possible..

-JasonL

**Comment by mkoza178** [comment]
Right, I'll talk with the product team and see if they're open to allowing that Back button color to be changed.

**Comment by JLewis12** [comment]
Please note, I am not using the "Already Subscriber" field this ticket was opened for.  The "Already subscribed" that your seeing on the /OMG2 presentation is the "LOG IN" field updated and recolored as a work around.. 

Sorry didn't mean to close this ticket
