### ISSUE TITLE
Slideshow not cycling

### ISSUE THREAD

**Issue by JLewis12** [mkoza178/Subscription-Panel-Implementation#7]
How do I unlink these 3 modules.  I assume this was set so we could have 3 images cycle on the slide show.  when you choose 1 all 3 change?

Using: https://test-subscribe.oregonlive.com/Example_1MarcCopy

![image](https://user-images.githubusercontent.com/26151269/35529196-2de690c8-04e5-11e8-9c1c-96f2b003c58c.png)

**Comment by mkoza178** [comment]
Checking on this one as well. Not seeing the Slides cycle nor when I click the arrow.

**Comment by mkoza178** [comment]
Check now. My slideshow setup was wrong. I needed different slideshow components. 
https://test-subscribe.oregonlive.com/Example_1MarcCopy

**Comment by JLewis12** [comment]
Working on my system.
